"""
Crawler Crawl Queue Validation and Serialization Schemas.
"""

from typing import Optional, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field


class CrawlInput(BaseModel):
    """Schema for raw page outputs generated by crawler agents."""
    url: str = Field(..., max_length=1000)
    raw_html: str = Field(...)
    headers: Optional[Dict[str, str]] = Field(default_factory=dict)
    http_status: int = Field(200, ge=100, le=599)
    response_time: Optional[float] = Field(None, ge=0.0)


class QueueItemDetail(BaseModel):
    """Schema for detailed queued crawl page records."""
    id: str
    url: str
    content_hash: str
    category: str
    language: str
    quality_score: int
    clean_text: str
    status: str
    created_at: datetime
    updated_at: datetime
    metadata_: Dict[str, Any] = Field(default_factory=dict, alias="metadata")

    model_config = {
        "from_attributes": True,
        "populate_by_name": True
    }
